### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
### POST: get recommendations (filtered)
POST http://localhost:8080/api/recommendations
Content-Type: application/json

{
  "location": "Shoreditch",
  "type": "FOOD",
  "budget": "CHEAP"
}

### POST: get recommendations (with coordinates)
POST http://localhost:8080/api/recommendations
Content-Type: application/json

{
  "latitude": 51.5035,
  "longitude": -0.1121,
  "type": "ACTIVITY",
  "budget": "CHEAP"
}

### POST: get recommendations (with coordinates)
POST http://localhost:8080/api/recommendations
Content-Type: application/json

{
  "latitude": 51.5035,
  "longitude": -0.1121,
  "type": "VIEW",
  "budget": "FREE",
  "excludePlacesIds": []
}
### POST: get recommendations (no filters / all)
POST http://localhost:8080/api/recommendations
Content-Type: application/json

{
}