INSERT INTO place (name, area, type, budget, description, latitude, longitude) VALUES
('Horizon 22', 'City of London', 'VIEW', 'FREE', 'London''s highest free public viewing gallery with panoramic skyline views.', 51.5149, -0.0805),
('Dishoom Shoreditch', 'Shoreditch', 'FOOD', 'CHEAP', 'Popular Bombay-style café with great atmosphere and strong brunch and dinner options.', 51.5247, -0.0783),
('Leake Street Arches', 'Waterloo', 'ACTIVITY', 'CHEAP', 'A graffiti-filled tunnel under Waterloo with street art, bars, food and pop-up entertainment.', 51.5031, -0.1132),
('Boxpark Shoreditch', 'Shoreditch', 'FOOD', 'CHEAP', 'Shipping-container street food mall with bars and loud music, easy central meeting point.', 51.5235, -0.0769),
('Camden Market', 'Camden', 'ACTIVITY', 'CHEAP', 'Sprawling canalside market of food stalls, vintage shops and music, easy to wander without plans.', 51.5414, -0.1466),
('Chin Chin Labs Camden', 'Camden', 'FOOD', 'CHEAP', 'Nitro ice-cream shop inside Camden Market, fun quick stop after browsing nearby stalls.', 51.5414, -0.1463),
('The Jazz Cafe', 'Camden', 'ACTIVITY', 'MEDIUM', 'Intimate live music venue with balcony seating, ideal for catching evening gigs after market hangs.', 51.5367, -0.1393),
('London Eye', 'South Bank', 'VIEW', 'EXPENSIVE', 'Huge riverside observation wheel offering classic skyline views, works well as a post-dinner highlight.', 51.5034, -0.1195),
('Southbank Centre', 'South Bank', 'ACTIVITY', 'FREE', 'Arts complex with free riverside seating, cafes and regular events, easy fallback plan near Waterloo.', 51.5061, -0.1164),
('Bussey Rooftop Bar', 'Peckham', 'ACTIVITY', 'MEDIUM', 'Rooftop bar with city views, covered seating and pizzas, good for sunset drinks after Peckham plans.', 51.4698, -0.0680),
('Peckham Levels', 'Peckham', 'ACTIVITY', 'CHEAP', 'Multi-storey creative hub in old car park with street food, studios and casual bar spaces.', 51.4709, -0.0686),
('Greenwich Market', 'Greenwich', 'FOOD', 'CHEAP', 'Covered historic market with varied street food stalls, nice meetup spot between park walks and river.', 51.4816, -0.0091),
('Greenwich Park Viewpoint', 'Greenwich', 'VIEW', 'FREE', 'Hilltop viewpoint by General Wolfe statue overlooking Canary Wharf and river, great low-effort scenic pause.', 51.4777, -0.0007),
('Granary Square Fountains', 'King''s Cross', 'VIEW', 'FREE', 'Large riverside-style square with choreographed fountains and plenty of seating, ideal between trains or meetups.', 51.5354, -0.1253),
('Coal Drops Yard', 'King''s Cross', 'ACTIVITY', 'MEDIUM', 'Restored railway arches now housing shops, bars and restaurants, relaxed place to drift after central commitments.', 51.5352, -0.1247),
('Dishoom King''s Cross', 'King''s Cross', 'FOOD', 'MEDIUM', 'Popular Bombay café-style restaurant near Granary Square, good for unhurried dinners before or after trains.', 51.5352, -0.1247),
('Camden Lock Canalside Steps', 'Camden', 'VIEW', 'FREE', 'Canalside steps overlooking Camden Lock, easy spot to sit with takeaway food and people-watch.', 51.5414, -0.1466),
('Leake Street Graffiti Tunnel', 'Waterloo', 'ACTIVITY', 'FREE', 'Long legal graffiti tunnel under Waterloo station, good for quick wander between South Bank plans.', 51.5025, -0.1132),
('Bar Italia', 'Soho', 'FOOD', 'CHEAP', 'Iconic late-opening Italian café ideal for post-theatre coffee or quick casual bite.', 51.5134, -0.1312),
('Chinatown Gerrard Street', 'Soho', 'FOOD', 'MEDIUM', 'Lively street packed with Chinese restaurants and bakeries, perfect for spontaneous group dinners or snacks.', 51.5118, -0.1317);